#!/bin/bash -p

#
# COPYRIGHT 2018, Cerebras Systems, Inc.
#

NAME=iptablesinit

start()
{
    route add default gw 10.0.0.1
}

stop()
{
    route del default gw 10.0.0.1
}


case "$1" in
    start)
        start ;;
    stop)
        stop ;;
    restart|reload)
        stop; start ;;
    *)
        echo "Usage: %0 {start|stop|restart}"
        exit 1
esac

exit 0
