#!/bin/bash -p

#
# COPYRIGHT 2018, Cerebras Systems, Inc.
#

NAME=iptablesinit
COMMAND=/usr/sbin/iptables

start()
{
    echo 1 > /proc/sys/net/ipv4/ip_forward
    $COMMAND -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    $COMMAND -A FORWARD -i eth0 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT
    $COMMAND -A FORWARD -i eth2 -o eth0 -j ACCEPT
    $COMMAND -A FORWARD -i eth0 -o eth3 -m state --state RELATED,ESTABLISHED -j ACCEPT
    $COMMAND -A FORWARD -i eth3 -o eth0 -j ACCEPT
}

stop()
{
    echo 0 > /proc/sys/net/ipv4/ip_forward
    $COMMAND -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    $COMMAND -D FORWARD -i eth0 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT
    $COMMAND -D FORWARD -i eth2 -o eth0 -j ACCEPT
    $COMMAND -D FORWARD -i eth0 -o eth3 -m state --state RELATED,ESTABLISHED -j ACCEPT
    $COMMAND -D FORWARD -i eth3 -o eth0 -j ACCEPT
}


case "$1" in
    start)
        start ;;
    stop)
        stop ;;
    restart|reload)
        stop; start ;;
    *)
        echo "Usage: %0 {start|stop|restart}"
        exit 1
esac

exit 0
